/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiLogPost } from '../fn/server-log/api-log-post';
import { ApiLogPost$Params } from '../fn/server-log/api-log-post';

@Injectable({ providedIn: 'root' })
export class ServerLogService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiLogPost()` */
  static readonly ApiLogPostPath = '/api/log';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLogPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiLogPost$Response(params: ApiLogPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return apiLogPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLogPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiLogPost(params: ApiLogPost$Params, context?: HttpContext): Observable<any> {
    return this.apiLogPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
