/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchResponse as SearchRankPresentationResponsesSearchResponse } from '../../models/SearchRank/Presentation/Responses/search-response';

export interface ApiGoogleSearchRankingGet$Params {
  Keyword: string;
  TargetUrl: string;
}

export function apiGoogleSearchRankingGet(http: HttpClient, rootUrl: string, params: ApiGoogleSearchRankingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchRankPresentationResponsesSearchResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGoogleSearchRankingGet.PATH, 'get');
  if (params) {
    rb.query('Keyword', params.Keyword, {});
    rb.query('TargetUrl', params.TargetUrl, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchRankPresentationResponsesSearchResponse>;
    })
  );
}

apiGoogleSearchRankingGet.PATH = '/api/google/search-ranking';
