/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchEngineResponse as SearchRankPresentationResponsesSearchEngineResponse } from '../../../../models/SearchRank/Presentation/Responses/search-engine-response';
export interface SearchResponse {
  keyword?: string | null;
  result?: SearchRankPresentationResponsesSearchEngineResponse;
  targetUrl?: string | null;
}
