/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { LoginRequest as SearchRankPresentationRequestsLoginRequest } from './models/SearchRank/Presentation/Requests/login-request';
export type { ServerLogRequest as SearchRankPresentationRequestsServerLogRequest } from './models/SearchRank/Presentation/Requests/server-log-request';
export type { LoginResponse as SearchRankPresentationResponsesLoginResponse } from './models/SearchRank/Presentation/Responses/login-response';
export type { SearchEngineResponse as SearchRankPresentationResponsesSearchEngineResponse } from './models/SearchRank/Presentation/Responses/search-engine-response';
export type { SearchResponse as SearchRankPresentationResponsesSearchResponse } from './models/SearchRank/Presentation/Responses/search-response';
